# Generated by Django 5.2.1 on 2025-06-09 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_alter_healthcareprovider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='billing',
            name='service_description',
            field=models.CharField(default='Consultation', max_length=200),
        ),
    ]
